app/models.py
from . import db
from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(40), unique=True)
    email = db.Column(db.String(100))
    password = db.Column(db.String(500))

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, TextAreaField, EmailField
from wtforms.validators import DataRequired, InputRequired, EqualTo, Length, Email, email_validator


class SignUpForm(FlaskForm):
    username = StringField('Username', validators=[
                           InputRequired(), Length(min=6, max=40, message=None)])
    email = EmailField('Email', validators=[InputRequired(), Email()])
    password = PasswordField('Password', validators=[
                             InputRequired(), Length(min=8, max=40, message=None)])
    submit = SubmitField('Sign Up')


class SignInForm(FlaskForm):
    username = StringField('Username', validators=[InputRequired()])
    password = PasswordField('Password', validators=[InputRequired()])
    submit = SubmitField('Sign In')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager


db = SQLAlchemy()


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = "not so secret key"
    from .bgmysql import cnx, sql_exec, mydbhost, mydbname, mydbpass, mydbuser

    # MySQL

    app.config['SQLALCHEMY_DATABASE_URI'] = f'mysql+pymysql://{mydbuser}:{mydbpass}@{mydbhost}/{mydbname}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User

    cur = cnx.cursor()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.signin'
    login_manager.login_message = ''
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

app/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from . import db
from .models import User
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from .forms import SignUpForm, SignInForm

auth = Blueprint('auth', __name__)


@auth.route('/signin', methods=['POST', 'GET'])
def signin():
    form = SignInForm()

    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data

        user = User.query.filter_by(username=username).first()

        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember=True)
                return redirect(url_for('views.index'))
            else:
                flash('Incorrect password!', category='danger')
        else:
            flash('Username does not exist!', category='danger')

    if current_user.is_authenticated:
        return redirect(url_for('views.index'))

    return render_template('accounts/signin.html', title="Sign In", form=form)


@auth.route('/signup', methods=['POST', 'GET'])
def signup():
    form = SignUpForm()

    if form.validate_on_submit():
        username = form.username.data
        email = form.email.data
        password = form.password.data

        user = User.query.filter_by(username=username).first()

        if user:
            flash('Username already exists', category='danger')
        else:
            new_user = User(username=username, email=email, password=generate_password_hash(
                password, method="sha256"))

            db.session.add(new_user)
            db.session.commit()

            login_user(new_user)

            return redirect(url_for('views.index'))

    if current_user.is_authenticated:
        return redirect(url_for('views.index'))

    return render_template('accounts/signup.html', title="Sign Up", form=form)


@auth.route('/signout')
@login_required
def signout():
    logout_user()
    return redirect(url_for('auth.signin'))

app/views.py
from functools import reduce
from flask import Blueprint, flash, render_template, redirect, request, url_for, jsonify
from flask_login import login_required, current_user
from werkzeug.security import check_password_hash, generate_password_hash
from jinja2 import TemplateNotFound

views = Blueprint('views', __name__)


@views.route('/')
@login_required
def index():
    return render_template('home/index.html', title="Home", user=current_user)


@views.route('/<template>')
@login_required
def route_template(template):
    try:
        if not template.endswith('.html'):
            template += '.html'

        return render_template("home/" + template)

    except TemplateNotFound:
        return render_template('home/page-404.html'), 404

    except:
        return render_template('home/page-500.html'), 500


@views.errorhandler(404)
def page_not_found():
    return render_template("home/page-404.html"), 404


@views.errorhandler(500)
def internal_server_error():
    return render_template("home/page-500.html"), 500

app/templates/accounts/signin.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="bg-light min-vh-100 d-flex flex-row align-items-center">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="card-group d-block d-md-flex row">
          <div class="card col-md-7 p-4 mb-0">
            <div class="card-body">
              <h1>Login</h1>
              <p class="text-medium-emphasis">
                {% if msg %}
                {{ msg | safe }}
                {% else %}
                Add your credentials
                {% endif %}
              </p>

              <form role="form" method="POST" action="{{ url_for('auth.signin') }}">

                {{ form.hidden_tag() }}

                <div class="input-group mb-3"><span class="input-group-text">
                    <svg class="icon">
                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-user"></use>
                    </svg></span>
                  {{ form.username(placeholder="Username", class="form-control") }}
                </div>
                <div class="input-group mb-4"><span class="input-group-text">
                    <svg class="icon">
                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-lock-locked"></use>
                    </svg></span>
                  {{ form.password(placeholder="Password", class="form-control", type="password") }}
                </div>
                {% include "partials/message-flasher.html" %}
                <div class="row">
                  <div class="col-6">
                    {{ form.submit(class="btn btn-primary px-4") }}
                  </div>
                  <div class="col-6 text-end">
                    <a href="#" class="btn btn-link px-0" type="button">Forgot Password?</a>
                  </div>
                </div>

              </form>

            </div>
          </div>
          <div class="card col-md-5 text-white bg-primary py-5">
            <div class="card-body text-center">
              <div>
                <h2>Sign up</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                  et dolore magna aliqua.</p>
                <a href="{{ url_for('auth.signup') }}" class="btn btn-lg btn-outline-light mt-3" type="button">Register
                  Now!</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

app/templates/accounts/signup.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Register {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="bg-light min-vh-100 d-flex flex-row align-items-center">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card mb-4 mx-4">
          <div class="card-body p-4">
            <h1>Register</h1>
            <p class="text-medium-emphasis">
              {% if msg %}
              {{ msg | safe }}
              {% else %}
              Create your account
              {% endif %}
            </p>

            <form role="form" method="POST" action="{{ url_for('auth.signup') }}">

              {{ form.hidden_tag() }}

              <div class="input-group mb-3"><span class="input-group-text">
                  <svg class="icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-user"></use>

                  </svg></span>
                {{ form.username(placeholder="Username", class="form-control") }}
              </div>

              <div class="input-group mb-3"><span class="input-group-text">
                  <svg class="icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-envelope-open"></use>
                  </svg></span>
                {{ form.email(placeholder="Email", class="form-control") }}
              </div>

              <div class="input-group mb-3"><span class="input-group-text">
                  <svg class="icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-lock-locked"></use>
                  </svg></span>
                {{ form.password(placeholder="Password", class="form-control", type="password") }}
              </div>

              {% include "partials/message-flasher.html" %}

              <div class="row">
                <div class="col-6">
                  {{ form.submit(class="btn btn-block btn-success") }}
                </div>
                <div class="col-6 text-end">
                  <a href="{{ url_for('auth.signin') }}" class="btn btn-link px-0" type="button">Login</a>
                </div>
              </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

app/templates/home/base-tooltips.html
{% extends "layouts/base.html" %}

{% block title %} UI Tooltips {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="body flex-grow-1 px-3">
    <div class="container-lg">
      <div class="callout callout-info bg-white">CoreUI Tooltip has been created as an extension of Bootstrap Tooltip. Tooltip is delivered with some new features, variants, and unique design that matches CoreUI Design System requirements.<br><br>For more information please visit our official
        <a href="https://coreui.io/docs/4.0/components/tooltips/" target="_blank">documentation</a>.
      </div>
      <div class="row">
        <div class="col-12">
          <div class="card mb-4">
            <div class="card-header"><strong>Tooltips</strong></div>
            <div class="card-body">
              <p>Hover over the links below to see tooltips:</p>
              <div class="example">
                <ul class="nav nav-tabs" role="tablist">
                  <li class="nav-item"><a class="nav-link active" data-coreui-toggle="tab" href="#preview-543" role="tab">
                      <svg class="icon me-2">
                        <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-media-play"></use>
                      </svg>Preview</a></li>
                  <li class="nav-item"><a class="nav-link" data-coreui-toggle="tab" href="#code-543" role="tab">
                      <svg class="icon me-2">
                        <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-code"></use>
                      </svg>Code</a></li>
                </ul>
                <div class="tab-content rounded-bottom">
                  <div class="tab-pane p-3 active preview" role="tabpanel" id="preview-543">
                    <p>Placeholder text to demonstrate some <a href="#" data-coreui-toggle="tooltip" data-coreui-original-title="Default tooltip">inline links</a> with tooltips. This is now just filler, no killer. Content placed here just to mimic the presence of <a href="#" data-coreui-toggle="tooltip" data-coreui-original-title="Another tooltip">real text</a>. And all that just to give you an idea of how tooltips would look when used in real-world situations. So hopefully you've now seen how <a href="#" data-coreui-toggle="tooltip" data-coreui-original-title="Another one here too">these tooltips on links</a> can work in practice, once you use them on <a href="#" data-coreui-toggle="tooltip" title="The last tip!">your own</a> site or project.</p>
                  </div>
                  <div class="tab-pane pt-1" role="tabpanel" id="code-543">
                    <script class="language-markup" type="text/plain">
                      <p>Placeholder text to demonstrate some <a href="#" data-coreui-toggle="tooltip" data-coreui-original-title="Default tooltip">inline links</a> with tooltips. This is now just filler, no killer. Content placed here just to mimic the presence of <a href="#" data-coreui-toggle="tooltip" data-coreui-original-title="Another tooltip">real text</a>. And all that just to give you an idea of how tooltips would look when used in real-world situations. So hopefully you've now seen how <a href="#" data-coreui-toggle="tooltip" data-coreui-original-title="Another one here too">these tooltips on links</a> can work in practice, once you use them on <a href="#" data-coreui-toggle="tooltip" title="The last tip!">your own</a> site or project.</p>
                    </script>
                  </div>
                </div>
              </div>
              <hr>
              <p>Hover over the buttons below to see the four tooltips directions: top, right, bottom, and left. Directions are mirrored when using Bootstrap in RTL.</p>
              <div class="example">
                <ul class="nav nav-tabs" role="tablist">
                  <li class="nav-item"><a class="nav-link active" data-coreui-toggle="tab" href="#preview-1038" role="tab">
                      <svg class="icon me-2">
                        <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-media-play"></use>
                      </svg>Preview</a></li>
                  <li class="nav-item"><a class="nav-link" data-coreui-toggle="tab" href="#code-1038" role="tab">
                      <svg class="icon me-2">
                        <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-code"></use>
                      </svg>Code</a></li>
                </ul>
                <div class="tab-content rounded-bottom">
                  <div class="tab-pane p-3 active preview" role="tabpanel" id="preview-1038">
                    <button class="btn btn-secondary" type="button" data-coreui-toggle="tooltip" data-coreui-placement="top" data-coreui-original-title="Tooltip on top">Tooltip on top</button>
                    <button class="btn btn-secondary" type="button" data-coreui-toggle="tooltip" data-coreui-placement="right" data-coreui-original-title="Tooltip on right">Tooltip on right</button>
                    <button class="btn btn-secondary" type="button" data-coreui-toggle="tooltip" data-coreui-placement="bottom" data-coreui-original-title="Tooltip on bottom">Tooltip on bottom</button>
                    <button class="btn btn-secondary" type="button" data-coreui-toggle="tooltip" data-coreui-placement="left" data-coreui-original-title="Tooltip on left">Tooltip on left</button>
                    <button class="btn btn-secondary" type="button" data-coreui-toggle="tooltip" data-coreui-html="true" data-coreui-original-title="<em>Tooltip</em> <u>with</u> <b>HTML</b>">Tooltip with HTML</button>
                  </div>
                  <div class="tab-pane pt-1" role="tabpanel" id="code-1038">
                    <script class="language-markup" type="text/plain">
                      <button class="btn btn-secondary" type="button" data-coreui-toggle="tooltip" data-coreui-placement="top" data-coreui-original-title="Tooltip on top">Tooltip on top</button>
                      <button class="btn btn-secondary" type="button" data-coreui-toggle="tooltip" data-coreui-placement="right" data-coreui-original-title="Tooltip on right">Tooltip on right</button>
                      <button class="btn btn-secondary" type="button" data-coreui-toggle="tooltip" data-coreui-placement="bottom" data-coreui-original-title="Tooltip on bottom">Tooltip on bottom</button>
                      <button class="btn btn-secondary" type="button" data-coreui-toggle="tooltip" data-coreui-placement="left" data-coreui-original-title="Tooltip on left">Tooltip on left</button>
                      <button class="btn btn-secondary" type="button" data-coreui-toggle="tooltip" data-coreui-html="true" data-coreui-original-title="&lt;em&gt;Tooltip&lt;/em&gt; &lt;u&gt;with&lt;/u&gt; &lt;b&gt;HTML&lt;/b&gt;">Tooltip with HTML</button>
                    </script>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-12">
          <div class="card mb-4">
            <div class="card-header"><strong>Tooltips</strong><span class="small ms-1"> Disabled elements</span></div>
            <div class="card-body">
              <p>Elements with the <code>disabled</code> attribute aren’t interactive, meaning users cannot focus, hover, or click them to trigger a tooltip (or popover). As a workaround, you’ll want to trigger the tooltip from a wrapper <code> &lt;div&gt;</code> or <code>&lt;span&gt;</code>, ideally made keyboard-focusable using <code>tabindex="0"</code>.</p>
              <div class="example">
                <ul class="nav nav-tabs" role="tablist">
                  <li class="nav-item"><a class="nav-link active" data-coreui-toggle="tab" href="#preview-487" role="tab">
                      <svg class="icon me-2">
                        <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-media-play"></use>
                      </svg>Preview</a></li>
                  <li class="nav-item"><a class="nav-link" data-coreui-toggle="tab" href="#code-487" role="tab">
                      <svg class="icon me-2">
                        <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-code"></use>
                      </svg>Code</a></li>
                </ul>
                <div class="tab-content rounded-bottom">
                  <div class="tab-pane p-3 active preview" role="tabpanel" id="preview-487"><span class="d-inline-block" tabindex="0" data-coreui-toggle="tooltip" data-coreui-original-title="Disabled tooltip">
                      <button class="btn btn-primary" type="button" disabled="">Disabled button</button></span>
                  </div>
                  <div class="tab-pane pt-1" role="tabpanel" id="code-487">
                    <script class="language-markup" type="text/plain"><span class="d-inline-block" tabindex="0" data-coreui-toggle="tooltip" data-coreui-original-title="Disabled tooltip">
                        <button class="btn btn-primary" type="button" disabled>Disabled button</button></span>
                    </script>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <!-- Plugins and scripts required by this view-->
  <script src="/static/assets/js/tooltips.js"></script>
  <script>
  </script>

{% endblock javascripts %}

app/templates/home/charts.html
{% extends "layouts/base.html" %}

{% block title %} Charts {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

  <link href="/static/assets/vendors/@coreui/chartjs/css/coreui-chartjs.css" rel="stylesheet">

{% endblock stylesheets %}

{% block content %}    

  <div class="body flex-grow-1 px-3">
    <div class="container-lg">
      <div class="row row-cols-2">
        <div class="col">
          <div class="card mb-4">
            <div class="card-header">Line Chart
              <div class="float-end"><a href="http://www.chartjs.org" target="_blank">docs</a></div>
            </div>
            <div class="card-body">
              <div class="c-chart-wrapper">
                <canvas id="canvas-1"></canvas>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card mb-4">
            <div class="card-header">Bar Chart
              <div class="float-end"><a href="http://www.chartjs.org" target="_blank">docs</a></div>
            </div>
            <div class="card-body">
              <div class="c-chart-wrapper">
                <canvas id="canvas-2"></canvas>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card mb-4">
            <div class="card-header">Doughnut Chart
              <div class="float-end"><a href="http://www.chartjs.org" target="_blank">docs</a></div>
            </div>
            <div class="card-body">
              <div class="c-chart-wrapper">
                <canvas id="canvas-3"></canvas>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card mb-4">
            <div class="card-header">Radar Chart
              <div class="float-end"><a href="http://www.chartjs.org" target="_blank">docs</a></div>
            </div>
            <div class="card-body">
              <div class="c-chart-wrapper">
                <canvas id="canvas-4"></canvas>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card mb-4">
            <div class="card-header">Pie Chart
              <div class="float-end"><a href="http://www.chartjs.org" target="_blank">docs</a></div>
            </div>
            <div class="card-body">
              <div class="c-chart-wrapper">
                <canvas id="canvas-5"></canvas>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card mb-4">
            <div class="card-header">Polar Area Chart
              <div class="float-end"><a href="http://www.chartjs.org" target="_blank">docs</a></div>
            </div>
            <div class="card-body">
              <div class="c-chart-wrapper">
                <canvas id="canvas-6"></canvas>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <script src="/static/assets/vendors/chart.js/js/chart.min.js"></script>
  <script src="/static/assets/vendors/@coreui/chartjs/js/coreui-chartjs.js"></script>
  <script src="/static/assets/js/charts.js"></script>
  <script>
  </script>

{% endblock javascripts %}

app/templates/home/register.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Register {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="bg-light min-vh-100 d-flex flex-row align-items-center">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-6">
            <div class="card mb-4 mx-4">
              <div class="card-body p-4">
                <h1>Register</h1>
                <p class="text-medium-emphasis">Create your account</p>
                <div class="input-group mb-3"><span class="input-group-text">
                    <svg class="icon">
                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-user"></use>

                    </svg></span>
                  <input class="form-control" type="text" placeholder="Username">
                </div>
                <div class="input-group mb-3"><span class="input-group-text">
                    <svg class="icon">
                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-envelope-open"></use>
                    </svg></span>
                  <input class="form-control" type="text" placeholder="Email">
                </div>
                <div class="input-group mb-3"><span class="input-group-text">
                    <svg class="icon">
                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-lock-locked"></use>
                    </svg></span>
                  <input class="form-control" type="password" placeholder="Password">
                </div>
                <div class="input-group mb-4"><span class="input-group-text">
                    <svg class="icon">
                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-lock-locked"></use>
                    </svg></span>
                  <input class="form-control" type="password" placeholder="Repeat password">
                </div>
                <button class="btn btn-block btn-success" type="button">Create Account</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

app/templates/includes/footer.html
<footer class="footer">
    <div>
        <a target="_blank" href="#">Flask CoreUI</a>
    </div>
    <div class="ms-auto">
        &copy; <a target="_blank" href="https://bit.ly/2VTDaxg">CoreUI.</a>
    </div>
</footer>

app/templates/includes/navigation.html
<header class="header header-sticky mb-4">
  <div class="container-fluid">
    <button class="header-toggler px-md-0 me-md-3" type="button"
      onclick="coreui.Sidebar.getInstance(document.querySelector('#sidebar')).toggle()">
      <svg class="icon icon-lg">
        <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-menu"></use>
      </svg>
    </button><a class="header-brand d-md-none" href="#">
      <svg width="118" height="46" alt="CoreUI Logo">
        <use xlink:href="/static/assets/brand/coreui.svg#full"></use>
      </svg></a>
    <ul class="header-nav d-none d-md-flex">
      <li class="nav-item"><a class="nav-link" href="#">Dashboard</a></li>
      <li class="nav-item"><a class="nav-link" href="#">Users</a></li>
      <li class="nav-item"><a class="nav-link" href="#">Settings</a></li>
    </ul>
    <ul class="header-nav ms-auto">
      <li class="nav-item"><a class="nav-link" href="#">
          <svg class="icon icon-lg">
            <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-bell"></use>
          </svg></a></li>
      <li class="nav-item"><a class="nav-link" href="#">
          <svg class="icon icon-lg">
            <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-list-rich"></use>
          </svg></a></li>
      <li class="nav-item"><a class="nav-link" href="#">
          <svg class="icon icon-lg">
            <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-envelope-open"></use>
          </svg></a></li>
    </ul>
    <ul class="header-nav ms-3">
      <li class="nav-item dropdown"><a class="nav-link py-0" data-coreui-toggle="dropdown" href="#" role="button"
          aria-haspopup="true" aria-expanded="false">
          <div class="avatar avatar-md"><img class="avatar-img" src="/static/assets/img/avatars/8.jpg"
              alt="user@email.com"></div>
        </a>
        <div class="dropdown-menu dropdown-menu-end pt-0">
          <div class="dropdown-header bg-light py-2">
            <div class="fw-semibold">Account</div>
          </div><a class="dropdown-item" href="#">
            <svg class="icon me-2">
              <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-bell"></use>
            </svg> Updates<span class="badge badge-sm bg-info ms-2">42</span></a><a class="dropdown-item" href="#">
            <svg class="icon me-2">
              <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-envelope-open"></use>
            </svg> Messages<span class="badge badge-sm bg-success ms-2">42</span></a><a class="dropdown-item" href="#">
            <svg class="icon me-2">
              <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-task"></use>
            </svg> Tasks<span class="badge badge-sm bg-danger ms-2">42</span></a><a class="dropdown-item" href="#">
            <svg class="icon me-2">
              <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-comment-square"></use>
            </svg> Comments<span class="badge badge-sm bg-warning ms-2">42</span></a>
          <div class="dropdown-header bg-light py-2">
            <div class="fw-semibold">Settings</div>
          </div><a class="dropdown-item" href="#">
            <svg class="icon me-2">
              <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-user"></use>
            </svg> Profile</a><a class="dropdown-item" href="#">
            <svg class="icon me-2">
              <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-settings"></use>
            </svg> Settings</a><a class="dropdown-item" href="#">
            <svg class="icon me-2">
              <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-credit-card"></use>
            </svg> Payments<span class="badge badge-sm bg-secondary ms-2">42</span></a><a class="dropdown-item"
            href="#">
            <svg class="icon me-2">
              <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-file"></use>
            </svg> Projects<span class="badge badge-sm bg-primary ms-2">42</span></a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{{ url_for('auth.signout') }}">
            <svg class="icon me-2">
              <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-account-logout"></use>
            </svg> Logout</a>
        </div>
      </li>
    </ul>
  </div>
  <div class="header-divider"></div>
  <div class="container-fluid">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb my-0 ms-2">
        <li class="breadcrumb-item">
          <!-- if breadcrumb is single--><span>Home</span>
        </li>
        <li class="breadcrumb-item active"><span>Dashboard</span></li>
      </ol>
    </nav>
  </div>
</header>

app/templates/partials/message-flasher.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}

<div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
  {{ message }}
  <button class="btn-close" type="button" data-coreui-dismiss="alert" aria-label="Close"></button>
</div>

{% endfor %}
{% endif %}
{% endwith %}